# -*- coding: utf-8 -*-
"""Algebra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LOh_Ks19hPdNz_VD3TDiL0RlKZ3XanUc
"""

import cmath

x = 5
y = 3

z = complex(x,y)
print("The real part bof complex is: ", end="")
print(z.real)

print("The imaginary part of complex number is : ", end="")
print(z.imag)

x = 5**4
y = 5**3
print(f"The answer is: {x}")
print(f"The answer is: {y}")

print(f"The result is: {x*y}")

def raise_to_power(base_num, pow_num):
  result = 1
  for index in range(pow_num):
    result = base_num ** base_num
    return result
    
print(raise_to_power(2, 2))

def test(h, w):
  result =  h ** w
  return result
print(test(3,3))

from fractions import Fraction

x = Fraction(300, 288) 
print(f"The answer is: {x}")

from fractions import Fraction

x = Fraction(300, 28) * Fraction(8, 4) + Fraction(101/4) * 5/3.4 * 100
print(f"""

Fraction(numerator, denominator)

The answer is: {int(x)}
The answer is: {float(x)}
The answer is: {type(x)}
The answer is: {str(x)}\nEnd
Doing Math with Python Programming Explore Algebra Statistics Calculus
""")

import IPython
js_code = '''
document.querySelector("#output-area").appendChild(document.createTextNode("hello world!"));
'''
display(IPython.display.Javascript(js_code))

# COMPLEX NUMBER
y = complex(2, 3)
print(f"The y is: {x} \nThe y is: {type(x)}")

from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))
  
  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))
